const ORDER_STATUSES = Object.freeze({
  DRAFT: "draft",
  PENDING: "pending",
  PENDING_PAYMENT: "pending_payment",
  CONFIRMED: "confirmed",
  PROCESSING: "processing",
  PARTIALLY_COMPLETED: "partially_completed",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  FAILED: "failed",
  WORK_IN_PROGRESS: "work_in_progress",
});

const TERMINAL_STATUSES = Object.freeze([
  ORDER_STATUSES.COMPLETED,
  ORDER_STATUSES.CANCELLED,
  ORDER_STATUSES.FAILED,
  ORDER_STATUSES.PARTIALLY_COMPLETED,
]);

const CANCELLABLE_STATUSES = Object.freeze([
  ORDER_STATUSES.PENDING,
  ORDER_STATUSES.CONFIRMED,
  ORDER_STATUSES.DRAFT,
  ORDER_STATUSES.WORK_IN_PROGRESS,
]);

const COMPLETABLE_STATUSES = Object.freeze([
  ORDER_STATUSES.PENDING,
  ORDER_STATUSES.CONFIRMED,
  ORDER_STATUSES.PROCESSING,
  ORDER_STATUSES.WORK_IN_PROGRESS,
]);

const ALL_STATUSES = Object.freeze(Object.values(ORDER_STATUSES));

export {
  ORDER_STATUSES,
  TERMINAL_STATUSES,
  CANCELLABLE_STATUSES,
  COMPLETABLE_STATUSES,
  ALL_STATUSES,
};
