// src/models/CommissionMonthlySummary.js
import mongoose from "mongoose";

/**
 * Commission Monthly Summary Model
 *
 * Stores aggregated commission data for each agent per month.
 * This model is used for:
 * 1. Historical reporting - view past months' commission performance
 * 2. Payment tracking - see which months are fully/partially paid
 * 3. Performance optimization - reduces query load on CommissionRecord collection
 * 4. Monthly archival - freezes data for completed months
 *
 * Created automatically on the 1st of each month by the archival cron job.
 */
const commissionMonthlySummarySchema = new mongoose.Schema(
  {
    // Time Period
    month: {
      type: String,
      required: true,
      // Format: "2025-01" (YYYY-MM)
      validate: {
        validator: function (v) {
          return /^\d{4}-\d{2}$/.test(v);
        },
        message: "Month must be in YYYY-MM format",
      },
    },
    year: {
      type: Number,
      required: true,
      min: 2020,
      max: 2100,
    },
    monthNumber: {
      type: Number,
      required: true,
      min: 1,
      max: 12,
    },
    monthName: {
      type: String,
      required: true,
      // e.g., "January 2025"
    },

    // Agent Information
    agentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // Commission Aggregates
    totalEarned: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
      // Total commission amount for the month (sum of all commission records)
    },
    totalPaid: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
      // Amount that has been paid to the agent
    },
    totalPending: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
      // Amount that is still pending payment
    },
    totalRejected: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
      // Amount that was rejected
    },
    totalExpired: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
      // Amount that expired without payment
    },

    // Performance Metrics
    orderCount: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
      // Total number of orders that generated commission
    },
    revenue: {
      type: Number,
      required: true,
      default: 0,
      min: 0,
      // Total revenue generated by agent for this month
    },
    commissionRate: {
      type: Number,
      required: true,
      min: 0,
      max: 100,
      // Average commission rate applied
    },

    // Payment Status
    paymentStatus: {
      type: String,
      enum: ["fully_paid", "partially_paid", "unpaid", "rejected", "expired"],
      required: true,
      default: "unpaid",
    },
    paymentPercentage: {
      type: Number,
      min: 0,
      max: 100,
      default: 0,
      // Percentage of total earned that has been paid (0-100)
    },

    // Commission Record References
    recordIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "CommissionRecord",
      },
    ],
    recordCount: {
      type: Number,
      default: 0,
      min: 0,
      // Total number of commission records for this month
    },

    // Archival Information
    isArchived: {
      type: Boolean,
      default: false,
      index: true,
      // True if this month has been archived (data is frozen)
    },
    archivedAt: {
      type: Date,
      // When this summary was created/archived
    },
    archivedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      // Super admin who triggered archival (null for automatic)
    },

    // Notes
    notes: {
      type: String,
      maxlength: 1000,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Compound Indexes for efficient queries
commissionMonthlySummarySchema.index({ agentId: 1, year: -1, monthNumber: -1 });
commissionMonthlySummarySchema.index({
  tenantId: 1,
  year: -1,
  monthNumber: -1,
});
commissionMonthlySummarySchema.index(
  { month: 1, agentId: 1 },
  { unique: true }
);
commissionMonthlySummarySchema.index({ paymentStatus: 1, isArchived: 1 });
commissionMonthlySummarySchema.index({ year: -1, monthNumber: -1 });

// Virtual for formatted date range
commissionMonthlySummarySchema.virtual("periodRange").get(function () {
  const startDate = new Date(this.year, this.monthNumber - 1, 1);
  const endDate = new Date(this.year, this.monthNumber, 0);
  return {
    start: startDate,
    end: endDate,
    formatted: `${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
  };
});

// Virtual for payment status badge
commissionMonthlySummarySchema.virtual("statusBadge").get(function () {
  const badges = {
    fully_paid: { color: "green", label: "Fully Paid", icon: "✓" },
    partially_paid: { color: "yellow", label: "Partially Paid", icon: "⚠" },
    unpaid: { color: "red", label: "Unpaid", icon: "○" },
    rejected: { color: "gray", label: "Rejected", icon: "✕" },
    expired: { color: "orange", label: "Expired", icon: "⌛" },
  };
  return badges[this.paymentStatus] || badges.unpaid;
});

// Virtual for formatted rate
commissionMonthlySummarySchema.virtual("formattedRate").get(function () {
  return `${this.commissionRate.toFixed(1)}%`;
});

// Method to update payment status based on amounts
commissionMonthlySummarySchema.methods.updatePaymentStatus = function () {
  if (this.totalEarned === 0) {
    this.paymentStatus = "unpaid";
    this.paymentPercentage = 0;
  } else if (this.totalRejected === this.totalEarned) {
    this.paymentStatus = "rejected";
    this.paymentPercentage = 0;
  } else if (this.totalExpired === this.totalEarned) {
    this.paymentStatus = "expired";
    this.paymentPercentage = 0;
  } else if (this.totalPaid === this.totalEarned) {
    this.paymentStatus = "fully_paid";
    this.paymentPercentage = 100;
  } else if (this.totalPaid > 0) {
    this.paymentStatus = "partially_paid";
    this.paymentPercentage = Math.round(
      (this.totalPaid / this.totalEarned) * 100
    );
  } else {
    this.paymentStatus = "unpaid";
    this.paymentPercentage = 0;
  }
  return this;
};

// Static method to find or create summary for a month
commissionMonthlySummarySchema.statics.findOrCreateForMonth = async function (
  agentId,
  tenantId,
  year,
  monthNumber
) {
  const monthStr = `${year}-${String(monthNumber).padStart(2, "0")}`;
  const monthName = new Date(year, monthNumber - 1, 1).toLocaleDateString(
    "en-US",
    {
      month: "long",
      year: "numeric",
    }
  );

  let summary = await this.findOne({
    agentId,
    month: monthStr,
  });

  if (!summary) {
    summary = new this({
      month: monthStr,
      year,
      monthNumber,
      monthName,
      agentId,
      tenantId,
    });
  }

  return summary;
};

// Static method to get summaries for an agent
commissionMonthlySummarySchema.statics.getAgentSummaries = async function (
  agentId,
  options = {}
) {
  const {
    limit = 12, // Last 12 months by default
    paymentStatus,
    startYear,
    endYear,
  } = options;

  const query = { agentId };

  if (paymentStatus) {
    query.paymentStatus = paymentStatus;
  }

  if (startYear || endYear) {
    query.year = {};
    if (startYear) query.year.$gte = startYear;
    if (endYear) query.year.$lte = endYear;
  }

  return await this.find(query)
    .sort({ year: -1, monthNumber: -1 })
    .limit(limit)
    .populate("agentId", "fullName email agentCode userType");
};

// Static method to get all summaries for a tenant
commissionMonthlySummarySchema.statics.getTenantSummaries = async function (
  tenantId,
  options = {}
) {
  const { limit = 100, paymentStatus, month } = options;

  const query = { tenantId };

  if (paymentStatus) {
    query.paymentStatus = paymentStatus;
  }

  if (month) {
    query.month = month;
  }

  return await this.find(query)
    .sort({ year: -1, monthNumber: -1 })
    .limit(limit)
    .populate("agentId", "fullName email agentCode userType");
};

const CommissionMonthlySummary = mongoose.model(
  "CommissionMonthlySummary",
  commissionMonthlySummarySchema
);

export default CommissionMonthlySummary;
